language: php
php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - git clone -b 2.0.x git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon/build/safe && phpize && ./configure --enable-phalcon && sudo make install
  - cd ../../../ && phpenv config-add ./tests/phalcon.ini
  - composer self-update
  - composer install --dev --prefer-source
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  phpunit -v &
  phpcs --standard=PSR2 --extensions=php --ignore=vendor/*,tests/*,cphalcon/* --warning-severity=0 ./

after_script:
  - ./vendor/bin/coveralls -v