language: php

php:
  - 5.5
  - 5.6

before_script:
  - git clone -b phalcon-v2.0.8 git://github.com/phalcon/cphalcon.git --depth=1 && cd cphalcon/build/ && ./install
  - cd ../../ && phpenv config-add ./tests/phalcon.ini
  - composer self-update
  - composer install --dev --prefer-source
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  phpunit -v &
  phpcs --standard=PSR2 --extensions=php --ignore=vendor/*,tests/*,cphalcon/* --warning-severity=0 ./

after_script:
  - ./vendor/bin/coveralls -v